# Part 1

In [2]:
import numpy as np

In [3]:
class Board:
    def __init__(self):
        self.board = np.zeros((5,5), dtype=int)
        self.marked = np.zeros((5,5))

    def read_from_lines(self, lines):
        for i in range(5):
            line_entries = [int(entry) for entry in lines[i].split(' ') if entry != '']
            self.board[i] = line_entries
    
    def check_called_number(self, called_number):
        if called_number in self.board:
            indices = np.where(self.board == called_number)
            self.marked[indices[0], indices[1]] = 1

    def check_win(self):
        return self.marked.all(axis=0).any() or self.marked.all(axis=1).any()

    def calculate_score(self, called_number):
        return (self.board * (self.marked==0)).sum() * called_number

In [4]:
def find_first_winner(called_numbers, boards):
    for called_number in called_numbers:
        for j in range(len(boards)):
            boards[j].check_called_number(called_number)
            if boards[j].check_win():
                print(f"Board {j+1} won!")
                print(boards[j].marked)
                return j, called_number

def part1(file_name):
    with open(file_name, 'r') as f:
        lines = [entry.strip() for entry in f.readlines()]
    
    called_numbers = [int(entry) for entry in lines[0].split(',')]
    print(called_numbers)

    number_of_boards = (len(lines)-1)//6
    print(number_of_boards)
    boards = dict()
    for j in range(number_of_boards):
        boards[j] = Board()
        boards[j].read_from_lines(lines[(2 + j*6):(2+5+(j+1)*6)])
    #print([board.board for board in boards.values()])

    winner_index, called_number = find_first_winner(called_numbers, boards)    
    print('score', boards[winner_index].calculate_score(called_number))

In [5]:
part1('example.txt')

[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
3
Board 3 won!
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]]
score 4512


In [6]:
part1('input.txt')

[18, 99, 39, 89, 0, 40, 52, 72, 61, 77, 69, 51, 30, 83, 20, 65, 93, 88, 29, 22, 14, 82, 53, 41, 76, 79, 46, 78, 56, 57, 24, 36, 38, 11, 50, 1, 19, 26, 70, 4, 54, 3, 84, 33, 15, 21, 9, 58, 64, 85, 10, 66, 17, 43, 31, 27, 2, 5, 95, 96, 16, 97, 12, 34, 74, 67, 86, 23, 49, 8, 59, 45, 68, 91, 25, 48, 13, 28, 81, 94, 92, 42, 7, 37, 75, 32, 6, 60, 63, 35, 62, 98, 90, 47, 87, 73, 44, 71, 55, 80]
100
Board 61 won!
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0.]]
score 25023


Yay, correct!! :)

# Part 2

figure out which board will win last - first, again, with the example input, where we are told the solution is the second board (index 1)

We need to adjust the ''find_first_winner'' function, so it now will show us the last winner. This means, we need to keep track of the winners.

We also can't break anymore after finding the winner, because we need to look for further winners. That means we don't know when to break and the strategy of calculating the score after returning from the function is wrong, as at that point more points on the board are marked than at winning time.

So I calculate the last winners score in the for loop.

In [7]:
def find_last_winner(called_numbers, boards):
    winners = []
    winner_call = 0
    for called_number in called_numbers:
        for j in range(len(boards)):
            if j not in winners:
                boards[j].check_called_number(called_number)
                if boards[j].check_win():
                    winners.append(j)
                    print(f"Board {j+1} won!")
                    winner_call = called_number
    return winners[-1], winner_call

def part2(file_name):
    with open(file_name, 'r') as f:
        lines = [entry.strip() for entry in f.readlines()]
    
    called_numbers = [int(entry) for entry in lines[0].split(',')]
    print(called_numbers)

    number_of_boards = (len(lines)-1)//6
    print(number_of_boards)
    boards = dict()
    for j in range(number_of_boards):
        boards[j] = Board()
        boards[j].read_from_lines(lines[(2 + j*6):(2+5+(j+1)*6)])
    #print([board.board for board in boards.values()])

    winner_index, called_number = find_last_winner(called_numbers, boards)    
    print('score', boards[winner_index].calculate_score(called_number))

In [8]:
part2('example.txt')

[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
3
Board 3 won!
Board 1 won!
Board 2 won!
score 1924


Correct answer for the example case, so now let's run it with the real input:

In [9]:
part2('input.txt')

[18, 99, 39, 89, 0, 40, 52, 72, 61, 77, 69, 51, 30, 83, 20, 65, 93, 88, 29, 22, 14, 82, 53, 41, 76, 79, 46, 78, 56, 57, 24, 36, 38, 11, 50, 1, 19, 26, 70, 4, 54, 3, 84, 33, 15, 21, 9, 58, 64, 85, 10, 66, 17, 43, 31, 27, 2, 5, 95, 96, 16, 97, 12, 34, 74, 67, 86, 23, 49, 8, 59, 45, 68, 91, 25, 48, 13, 28, 81, 94, 92, 42, 7, 37, 75, 32, 6, 60, 63, 35, 62, 98, 90, 47, 87, 73, 44, 71, 55, 80]
100
Board 61 won!
Board 65 won!
Board 85 won!
Board 91 won!
Board 98 won!
Board 17 won!
Board 60 won!
Board 90 won!
Board 23 won!
Board 37 won!
Board 29 won!
Board 32 won!
Board 71 won!
Board 50 won!
Board 1 won!
Board 13 won!
Board 9 won!
Board 52 won!
Board 26 won!
Board 38 won!
Board 45 won!
Board 74 won!
Board 92 won!
Board 35 won!
Board 66 won!
Board 55 won!
Board 86 won!
Board 100 won!
Board 6 won!
Board 14 won!
Board 27 won!
Board 34 won!
Board 83 won!
Board 12 won!
Board 47 won!
Board 75 won!
Board 99 won!
Board 3 won!
Board 78 won!
Board 81 won!
Board 41 won!
Board 18 won!
Board 44 won!
Board 

Also correct! Yay :)