# Part 1

- read in a grid of one-digit numbers
- consider 4 direct neighbors of each entry
- if all 4 neighbors are lower than entry, this is a low point
- identify low points

Warning: corner cases don't have 4 neighbors of course

The risk level of a low point is 1 plus its height.

Sum up the risk levels of all low points

In [3]:
import numpy as np


In [4]:
def create_grid(lines):
    grid = np.zeros((len(lines), len(lines[0])), dtype=int)
    for index, line in enumerate(lines):
        entries = [int(entry) for entry in list(line)]
        grid[index] = entries
    return grid

def get_neighbors(x, y, grid):
    neighbors = []
    if x+1 < grid.shape[0]:
        neighbors.append(grid[x+1, y])
    if x-1 >= 0:
        neighbors.append(grid[x-1, y])
    if y+1 < grid.shape[1]:
        neighbors.append(grid[x, y+1])
    if y-1 >= 0:
        neighbors.append(grid[x, y-1])
    return neighbors

def is_low_point(x, y, grid):
    neighbors = get_neighbors(x, y, grid)
    return all([grid[x, y] < neighbor for neighbor in neighbors])
        
def get_score(x, y, grid):
    return grid[x, y] + 1

def part1(file_name):
    with open(file_name, 'r') as f:
        lines = [line.strip() for line in f.readlines()]
    
    score = 0

    grid = create_grid(lines)
    for x in range(grid.shape[0]):
        for y in range(grid.shape[1]):
            if is_low_point(x, y, grid):
                score += get_score(x, y, grid)
    print(score)

In [3]:
part1('example.txt')

15


In [4]:
part1('input.txt')

444


# Part 2

Find basins
- height 9 is never part of a basin
- all other points are in exactly one basin
- every low point has a basin around it

Get three largest basins, multiply their sizes (points in the basin) together

In [21]:
def count_basin_neighbors(x, y, grid, visited):
    # print('x', x, 'y', y)
    visited[x, y] = 1
    count = 0
    if x+1 < grid.shape[0]:
        if grid[x+1, y] < 9:
            if not visited[x+1, y]:
                count += 1 + count_basin_neighbors(x+1, y, grid, visited)
    if x-1 >= 0:
        if grid[x-1, y] < 9:
            if not visited[x-1, y]:
                count += 1 + count_basin_neighbors(x-1, y, grid, visited)
    if y+1 < grid.shape[1]:
        if grid[x, y+1] < 9:
            if not visited[x, y+1]:
                count += 1 + count_basin_neighbors(x, y+1, grid, visited)
    if y-1 >= 0:
        if grid[x, y-1] < 9:
            if not visited[x, y-1]:
                count += 1 + count_basin_neighbors(x, y-1, grid, visited)
    return count

def get_basin_size(x, y, grid):
    visited = np.zeros(grid.shape, dtype=int)
    size = count_basin_neighbors(x, y, grid, visited) + 1
    return size

def part2(file_name):
    with open(file_name, 'r') as f:
        lines = [line.strip() for line in f.readlines()]
    
    basin_sizes = []

    grid = create_grid(lines)
    print(grid)
    
    for x in range(grid.shape[0]):
        for y in range(grid.shape[1]):
            if is_low_point(x, y, grid):
                basin_sizes.append(get_basin_size(x, y, grid))
    basin_sizes.sort(reverse=True)
    print('basin sizes', basin_sizes)
    print('score', basin_sizes[0]*basin_sizes[1]*basin_sizes[2])

In [22]:
part2('example.txt')

[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
basin sizes [14, 9, 9, 3]
score 1134


In [23]:
part2('input.txt')

[[7 6 7 ... 6 7 8]
 [4 5 6 ... 5 6 7]
 [5 6 7 ... 4 5 6]
 ...
 [6 5 6 ... 5 6 7]
 [3 4 5 ... 4 7 8]
 [4 5 6 ... 5 6 7]]
basin sizes [107, 105, 104, 102, 99, 95, 94, 94, 91, 89, 89, 86, 86, 86, 83, 83, 82, 81, 81, 80, 77, 77, 74, 73, 73, 72, 72, 69, 68, 68, 67, 67, 67, 66, 66, 66, 65, 65, 65, 65, 64, 64, 64, 62, 61, 61, 61, 60, 60, 60, 59, 58, 57, 57, 56, 56, 55, 54, 53, 52, 51, 51, 51, 51, 50, 49, 48, 47, 47, 47, 46, 46, 45, 44, 44, 44, 42, 42, 42, 41, 41, 41, 40, 40, 39, 38, 38, 37, 36, 36, 35, 35, 34, 32, 32, 32, 32, 32, 31, 31, 31, 31, 29, 28, 27, 27, 27, 26, 26, 26, 26, 25, 25, 24, 24, 24, 23, 23, 22, 22, 22, 22, 22, 22, 21, 21, 21, 21, 20, 20, 20, 20, 19, 18, 18, 18, 18, 18, 17, 17, 17, 17, 16, 16, 16, 16, 15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 12, 12, 12, 11, 11, 10, 10, 10, 10, 9, 9, 9, 8, 7, 7, 7, 6, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2]
score 1168440
