In [52]:
import re
import numpy as np

# Part 1

for now only consider horizontal lines, where either x1=x2 or y1=y2

In [64]:
def enter_line(grid, x1, y1, x2, y2):
    if x1 == x2:
        for y in range(min(y1, y2), max(y1, y2)+1):
            grid[x1, y] += 1
    if y1 == y2:
        for x in range(min(x1, x2), max(x1, x2)+1):
            grid[x, y1] += 1

In [67]:
def part_1(file_name):
    with open(file_name, 'r') as f:
        lines = f.readlines()
        lines = [entry.strip() for entry in lines]

    max_x = 0
    max_y = 0
    for line in lines:
        x1, y1, x2, y2 = [int(entry) for entry in re.sub('[^0-9]', ' ', line).split()]
        max_x = max(max_x, x1, x2)
        max_y = max(max_y, y1, y2)

    print('max x', max_x, 'max y', max_y)
    grid = np.zeros((max_x+1, max_y+1), dtype=int)

    for line in lines:
        x1, y1, x2, y2 = [int(entry) for entry in re.sub('[^0-9]', ' ', line).split()]
        enter_line(grid, x1, y1, x2, y2)
    print('score', (grid >= 2).sum())

In [60]:
# lines[0].split(',')
# #[int(i) for i in lines[0].split() if i.isdigit()]
# only_number = re.sub('[^0-9]', ' ', lines[0]).split()
# only_number

['0', '9', '5', '9']

In [68]:
part_1('example.txt')

max x 9 max y 9
score 5


In [69]:
part_1('input.txt')

max x 988 max y 989
score 4655


# Part 2

now we also consider 45 degree diagonal lines.. sad face

In [92]:
def enter_line_extended(grid, x1, y1, x2, y2):
    if x1 == x2:
        for y in range(min(y1, y2), max(y1, y2)+1):
            grid[y, x1] += 1
        return
    if y1 == y2:
        for x in range(min(x1, x2), max(x1, x2)+1):
            grid[y1, x] += 1
        return
    # I guess all lines here have to be diagonal, feels hacky but whatever
    line_length = abs(x1-x2)+1
    step_x = 1 if x2-x1 > 0 else -1
    step_y = 1 if y2-y1 > 0 else -1
    for i in range(line_length):
        new_x = x1 + i*step_x
        new_y = y1 + i*step_y
        grid[new_y, new_x] += 1

In [104]:
def part_2(file_name):
    with open(file_name, 'r') as f:
        lines = f.readlines()
        lines = [entry.strip() for entry in lines]

    max_x = 0
    max_y = 0
    for line in lines:
        x1, y1, x2, y2 = [int(entry) for entry in re.sub('[^0-9]', ' ', line).split()]
        max_x = max(max_x, x1, x2)
        max_y = max(max_y, y1, y2)

    print('max x', max_x, 'max y', max_y)
    grid = np.zeros((max_y+1, max_x+1), dtype=int)

    for line in lines:
        x1, y1, x2, y2 = [int(entry) for entry in re.sub('[^0-9]', ' ', line).split()]
        #print(line)
        enter_line_extended(grid, x1, y1, x2, y2)
        #print(grid)
    print(grid)
    print('score', (grid >= 2).sum())

In [105]:
part_2('example.txt')

max x 9 max y 9
[[1 0 1 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 2 0 0]
 [0 0 2 0 1 0 1 1 1 0]
 [0 0 0 1 0 2 0 2 0 0]
 [0 1 1 2 3 1 3 2 1 1]
 [0 0 0 1 0 2 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [2 2 2 1 1 1 0 0 0 0]]
score 12


In [106]:
part_2('input.txt')

max x 988 max y 989
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
score 20500
